docs/zh/blog/2018-12-18-Apache-SkyWalking-advanced-usage.md, docs/zh/blog/2018-12-21-SkyWalking-apm-sniffer-beginning.md, docs/zh/blog/README.md
=> add md 'Apache-SkyWalking-advanced-usage'

docs/zh/blog/2018-12-21-SkyWalking-source-code-read.md, docs/zh/blog/README.md, package-lock.json
* add md '2018-12-21-SkyWalking-source-code-read'
=> add SkyWalking source code read

docs/zh/blog/2019-01-12-skywalking-elasticsearch-basic.md, docs/zh/blog/README.md
添加关于elasticsearch 因basic验证导致skywalking无法调用问题
=> 添加关于elasticsearch 因basic验证导致skywalking无法调用问题

docs/team/README.md
I think that this alphabeta have a wrong spelling.Do you think?
=> modify alphabeta -> alphabet

docs/README.md, docs/events/README.md, docs/team/README.md, docs/zh/README.md, docs/zh/events/README.md, docs/zh/team/README.md
Add Han Liu as a new committer
=> add committer

docs/zh/blog/2020-04-28-skywalking-and-mosn.md, docs/zh/blog/README.md
- This blog is eager to be merged at Apr 29, 2020 while MOSN v0.12
release.
=> blog: SkyWalking support MOSN

docs/README.md, docs/events/README.md, docs/team/README.md, docs/zh/README.md, docs/zh/events/README.md, docs/zh/team/README.md
@wu-sheng Thanks for your long time help, I'm glad to be a committer.
=> add new committer

docs/.vuepress/config.js, docs/README.md, docs/downloads/README.md, docs/events/README.md, docs/zh/README.md, docs/zh/downloads/README.md, docs/zh/events/README.md
As the title indicates, add swck 0.1.0 relevant events and links to the website.
=> Add swck 0.1.0 release

content/zh/2020-08-13-cloud-native-academy/index.md, content/zh/2020-10-25-coscon20-swck/index.md
[视频] 云原生学院 - 后分布式追踪时代的性能问题定位 —— 方法级性能剖析
=> add: new blog

content/zh/2020-11-21-What-do-we-see-at-the-Apache-SkyWalking-2020-DevCon-event/index.md
Process images without folding
=> Process images without folding

.github/workflows/deploy.yaml
Was run in branch and looks good https://github.com/apache/skywalking-website/runs/1442570161?check_suite_focus=true
=> Fix GHA workflow directory name

content/team/_index.md
- The member list is incomplete on the team page, and it is not sorted in alphabetical order.
- Add more repos' contributor list
=> Update team page

data/dockerImages.yml, data/docs.yml, data/releases.yml, layouts/shortcodes/dockerhub-block.html, layouts/shortcodes/downloads-block.html, themes/docsy/layouts/docs/baseof.html
feature: change static files to templates
=> change static files to templates

content/events/release-apache-skywalking-cli-0-5-0/index.md, data/releases.yml
I'm not sure if I'm missing anything，please check.
=> CLI 0.5.0 Release Event

content/events/welcome-gui-cao-as-new-committer/index.md, content/team/_index.md
Pending on the secretary's ICLA filed mail.
=> Welcome Gui Cao as new committer

content/team/_index.md
=> Add a committer

themes/docsy/assets/scss/_blog.scss
=> Fix: blog screen adaptation

content/blog/e2e-design/index.md
This is opened to get early feedback about the design, technical details should be shared later.
Appreciate if @hanahmily can take a look at the KinD part and @mrproliu can take a look at the locally debugging part (you complained about that mostly 😅)
=> blog: add the design doc of NGE2E

content/_index.html
- https://skywalking.apache.org/#demo
- https://skywalking.apache.org/#feature
- https://skywalking.apache.org/#events
- https://skywalking.apache.org/#users
=> Add anchor point

content/_index.html
- https://skywalking.apache.org/#arch
=> add arch hook

data/docs.yml
Fix https://github.com/apache/skywalking/issues/6041
=> Add more new repos to the website.

.github/workflows/deploy.yaml, README.md
Add the auto-deployment back via using GHA that was approved by infra
=> Add auto-deploy back

themes/docsy/assets/scss/_content.scss
=> fix word break

layouts/shortcodes/bilibili.html, themes/docsy/assets/scss/_blog.scss
Fixed  size scale  of bilibili video when the phone is vertical.
screen shot
=> Fixed  size scale  of bilibili video

content/events/release-apache-skywalking-cloud-on-kubernetes-0-2-0/index.md, data/docs.yml, data/releases.yml
As the title indicated, the changes intend to update links and references to release 0.2.0, adding this release news. 
=> Release SWCK 0.2.0

data/docs.yml, docs.js, package.json, themes/docsy/layouts/projectDoc/baseof.html
This pr works after [#6391](https://github.com/apache/skywalking/pull/6391) is merged.
=> Add latest doc

data/docs.yml, doc.sh, docs.js
=> Optimization: Quit deployment when error

config.toml
Update `config.toml` to remove the info of last time to modify
=> Update `config.toml` to remove the info of last time to modify

docs.js
=> Fix docs.js

docs.js
=> Fix `docs.js`

data/docs.yml
=> add satellite doc

LICENSE, docs.js, themes/docsy/assets/scss/_custom_project_doc.scss, themes/docsy/assets/scss/_styles_project.scss, themes/docsy/assets/scss/sidebar-menu.scss, themes/docsy/layouts/partials/sidebar-menu.html, themes/docsy/layouts/partials/sidebar-submenu.html, themes/docsy/layouts/projectDoc/baseof.html, themes/docsy/static/js/sidebar-menu.js
=> Refactor doc menu

.gitignore, themes/docsy/assets/scss/sidebar-menu.scss, themes/docsy/layouts/partials/sidebar-menu.html, themes/docsy/layouts/projectDoc/baseof.html
Fix: the doc menu shakes when page reloads
=> Fix: the doc menu shakes when page reloads

content/events/release-apache-skwaylking-satellite-0-1-0/index.md, data/releases.yml
add release-satellite-0.1.0 event
=> add release-satellite-0.1.0 event

themes/docsy/assets/scss/_custom_project_doc.scss, themes/docsy/assets/scss/_custom_slider.scss, themes/docsy/assets/scss/sidebar-menu.scss, themes/docsy/layouts/projectDoc/baseof.html
A feature of doc menu for mobile.
screenshot:
=> A featur of doc menu for mobile

content/events/release-apache-skywalking-client-js-0-4-0/index.md, data/docs.yml, data/releases.yml
=> docs: update docs for client js

data/releases.yml
Add distribution for client js on the downloads page.
=> docs: add distribution for client js on the downloads page

config.toml, docs.js
- checked date:
- checked `exit` when fetch errors:
=> Fix lastmod date

layouts/shortcodes/downloads-block.html, themes/docsy/layouts/downloads/baseof.html
=> Send data to google analytics when click download links

themes/docsy/layouts/downloads/baseof.html
=> Fix analytics

docs.js
=> Fix docs imgUrl

themes/docsy/assets/scss/_blog.scss, themes/docsy/assets/scss/_custom_project_doc.scss, themes/docsy/layouts/partials/toc.html
The fixed-width makes the document outline look unclear.
Remove it will make it look better.
=> style: remove width from doc outline

content/_index.html, themes/docsy/assets/scss/_custom_home.scss, themes/docsy/layouts/partials/scripts-home.html
=> Optimize the UI style of the home page

content/_index.html, themes/docsy/assets/scss/_custom_home.scss
=> Fix: the width of active box

content/events/release-apache-skywalking-cloud-on-kubernetes-0-3-0/index.md, data/docs.yml, data/releases.yml
=> Release SWCK 0.3.0

content/events/release-apache-skywalking-apm-8-5-0/index.md, data/docs.yml, data/releases.yml
Let's wait for the release to complete.
=> Release 8.5.0

README.md, docs.js, themes/docsy/assets/scss/_custom_project_doc.scss, themes/docsy/assets/scss/_sidebar-toc.scss, themes/docsy/layouts/projectDoc/baseof.html
=> Feat: Document version selector

layouts/shortcodes/downloads-block.html, themes/docsy/assets/scss/_custom_downloads.scss
=> refactor: download dropdown styles

content/events/release-apache-skywalking-kong-0.1.0/index.md, data/docs.yml, data/releases.yml
Reverts apache/skywalking-website#268
=> Revert "release skywalking-kong version 0.1.0"

README.md, content/events/skywalkingday-2021/index.md, themes/docsy/assets/js/event-popup.js, themes/docsy/assets/scss/_event-popup.scss, themes/docsy/layouts/partials/event-popup.html
- Double-filter the events that will be displayed in popover when build project and when enter the page
- Show different styles based on the count of events
- Display the background image of the most recent event
screenshots:
=> feat: Popover supports multiple events

content/downloads/_index.md, data/releases.yml, layouts/shortcodes/dockerhub-block.html, layouts/shortcodes/downloads-block.html, themes/docsy/assets/scss/_custom_docs.scss, themes/docsy/assets/scss/_custom_downloads.scss
=> refactor: The content category of the downloads-page

content/events/release-apache-skywalking-client-js-0.5.0/index.md, themes/docsy/assets/scss/_styles_project.scss
bug: list-style is not displayed
fixed screenshot:
=> fix: mobile style

layouts/shortcodes/contributors.html, scripts/team.js
Remove duplicate anonymous contributors for each repo.
=> fix: Remove duplicate anonymous contributors for each repo

content/team/_index.md
@kezhenxu94 Sorry, I suddenly found that I just added the wrong position.
=> Update committer list.

content/events/release-apache-skywalking-client-js-0-6-0/index.md, data/docs.yml, data/releases.yml
Add client-js release event.
Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>
=> feat: add client-js release event

README.md, content/blog/2021-07-12-500-contributors-mark/index.md, content/downloads/_index.md, themes/docsy/assets/scss/_main-container.scss, themes/docsy/layouts/partials/event-popup.html
- support popover for all articles
- styles for table/downloads-page
=> feat: support popover for all articles

content/_index.html, themes/docsy/layouts/shortcodes/blocks/feature.html
=> Change the slack joining guidance

layouts/shortcodes/dockerhub-block.html, layouts/shortcodes/downloads-block.html, themes/docsy/assets/js/active.js, themes/docsy/assets/scss/_custom_docs.scss, themes/docsy/assets/scss/_custom_downloads.scss, themes/docsy/layouts/docs/baseof.html, themes/docsy/layouts/downloads/baseof.html, themes/docsy/layouts/partials/active-scripts.html
=> feat: The anchor activation for project and download page

content/_index.html
Just adding a missing one to the sentence.
=> Add Python agent to the list

data/docs.yml, layouts/shortcodes/contributors.html, scripts/team.js, themes/docsy/assets/js/active.js, themes/docsy/assets/scss/_custom_docs.scss, themes/docsy/layouts/docs/baseof.html
=> Add a anchor for More language agents to Ecosystem

data/docs.yml
=> Retire Docker repo

data/docs.yml
Part of https://github.com/apache/skywalking/issues/7687
=> Pull docs from python repo

content/events/release-apache-skywalking-cli-0-8-0/index.md, data/releases.yml
Wait for @kezhenxu94 to move artifacts to `https://dist.apache.org/repos/dist/release/skywalking/`, then this PR can be merged.
=> Release CLI 0.8.0

content/events/release-apache-skywalking-apm-8-8-0/index.md, data/docs.yml, data/releases.yml
Pending on release vote, it should be done tomorrow.
=> Set up 8.8.0 release event.

content/team/_index.md
=> Update the committer list

content/events/release-apache-skywalking-cloud-on-kubernetes-0-4-0/index.md, data/docs.yml, data/releases.yml
=> Release swck 0.4.0

data/docs.yml
Wait for https://github.com/SkyAPM/transporter-plugin-for-skywalking/pull/7 ready to merge.
=> Add Transporter Plugins repository

data/docs.yml
Fixing a spelling problem and making it more contextual appealing.
=> Minor enhancement to the showcase repo description

docs.js
=> Fix the documentation file

content/events/release-apache-skywalking-apm-8-9-0/index.md, data/docs.yml, data/releases.yml
=> Release OAP 8.9.0

content/blog/2021-12-06-extend-skywalking-with-nbb/index.md
=> Remove dangling header

content/blog/2021-12-06-extend-skywalking-with-nbb/index.md
Added a link to github org, cleaned up some wording
=> Blog post retouching

content/blog/2021-12-13-skywalking-nginx-agent-integration/index.md
introduce integrating skywalking-nginx-lua to nginx
=> introduce integrating skywalking-nginx-lua to nginx

content/events/release-apache-skywalking-cloud-on-kubernetes-0-5-0/index.md, data/docs.yml, data/releases.yml
=> Release swck 0.5.0

content/blog/2021-12-21-better-observability-for-chaos-engineering/index.md
Signed-off-by: FingerLeader <wanxfinger@gmail.com>
=> fix image path and date

layouts/shortcodes/downloads-block.html
=> Fixed download statistics

content/zh/2022-03-14-the-apache-community/index.md
Signed-off-by: tison <wander4096@gmail.com>
cc @wu-sheng I'm unsure whether it should take another title 🤔
=> Add blog The Apache Community

content/zh/2022-03-25-skywalking-source-code-analyzation/index.md
I am honored to be invited to submit the source code analyzation video I recorded to the official Chinese blog. I have written the blog content according to the specifications, please correct me.
=> add new post - skywalking-source-code-analyzation

scripts/team.js
Exit the building program when the graphs request is in error
=> fix: Exit the building program when the graphs request is in error

content/events/release-apache-skywalking-client-js-0-8-0/index.md, data/docs.yml, data/releases.yml
Add client js release event.
Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>
=> docs: add client js release event

content/events/release-apache-skywalking-client-js-0-8-0/index.md
Fixes date.
Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>
=> docs: update date

content/events/summer-ospp-2022/readme.md
Add switches for monitoring items.
=> Summer 2022 - SkyAPM-PHP

content/events/release-apache-skywalking-java-agent-8-10-0/index.md, data/docs.yml, data/releases.yml
Pending on release vote https://lists.apache.org/thread/vdqhy3hybyyohxt3rnkzx57hht9bt4bw
=> Release Java agent 8.10.0

content/events/summer-ospp-2022/readme.md
- Adds the concrete project task for https://github.com/apache/skywalking/discussions/8883
- Fixes some grammar issues in text
=> Add new project for OSPP2022

content/events/summer-ospp-2022/readme.md
=> Add two projects to OSPP 2022 event

content/events/summer-ospp-2022/readme.md
=> Update the mentor of SWCK

data/docs.yml
=> Add banyandb official document

content/events/release-apache-skywalking-banyandb-0-1-0/index.md, data/docs.yml, data/releases.yml
=> Publish BanyanDB 0.1.0

assets/scss/_custom_home.scss, content/_index.html
=> Change the position of the demo entrance

content/events/release-apache-skywalking-java-agent-8-11-0/index.md, data/docs.yml, data/releases.yml
=> Release Java agent 8.11.0

content/team/_index.md
=> Move Jaijing Lu to PMC list

content/team/_index.md
Add new committer: Jiemin Xia.
=> Add new committer.

content/team/_index.md, themes/docsy/layouts/partials/script-team.html, themes/docsy/layouts/partials/scripts-home.html, themes/docsy/static/js/initMergedGraph.js
=> Bug fix: contributions chart is occasionally not displayed

content/blog/2022-08-11-kongcast-20-distributed-tracing-using-skywalking-kong/index.md, content/blog/2022-08-11-kongcast-20-distributed-tracing-using-skywalking/index.md
Signed-off-by: Andrew Kew <andrew@quadcorps.co.uk>
New conference video, Kongcast - an interview with Andrew Kew about distributed tracing, demoing Apache SkyWalking and Kong API Gateway
=> New blog post with Kongcast video showing SkyWalking demo

assets/scss/_custom_team.scss
Displaying exception when Safari version is lower than 14.4 on iOS:
=> Solve a browser compatibility problem

content/events/release-apache-skywalking-java-agent-8-12-0/index.md, data/docs.yml, data/releases.yml
=> Release Java agent 8.12.0

content/events/release-apache-skywalking-cloud-on-kubernetes-0-7-0/index.md, data/docs.yml, data/releases.yml
Signed-off-by: Ye Cao <dashanjic@gmail.com>
=> Release swck v0.7.0

content/_index.html
=> Add missing agent and chore

content/team/_index.md
Due to <https://skywalking.apache.org/events/welcome-heyanlong-xiajiemin-join-the-pmc/>.
=> Move Jiemin and Yanlong to PMC list.

content/_index.html
In the last two years, SkyWalking community's landscape changed a lot. From mostly tracing and service mesh, move to larger scopes covering such as infra, browser, middleware servers, gateway.
I am planning to reword the document on the front page to make them all clear about our key features.
=> Re-words new features of SkyWalking

content/team/_index.md
=> Update team list

content/_index.html, themes/docsy/layouts/partials/scripts-home.html
=> Add an anchor for demo button

assets/scss/_buttons.scss, scripts/team.js
=> Uniform button rounding  style & change the time interval between requests

content/events/release-apache-skywalking-banyandb-0-3-0/index.md, data/docs.yml, data/releases.yml
=> Publish banyandb 0.3.0

data/docs.yml, data/releases.yml
Signed-off-by: Megrez Lu <lujiajing1126@gmail.com>
=> Release banyandb java-client 0.3.0

content/events/release-apache-skywalking-python-1-0-0/index.md, data/docs.yml, data/releases.yml
Release notes added, version bumped.
Also fixed few nits in other places.
=> Release Python agent 1.0.0

assets/scss/_custom_home.scss, content/_index.html
Pending on demo new deployment
=> Add a new option for Grafana UI preview.

config.toml, themes/docsy/assets/scss/_nav.scss, themes/docsy/layouts/partials/navbar.html, themes/docsy/layouts/partials/sidebar-skywalking.html
=> Add Chinese information navigation

content/team/_index.md
Move myself from the committer list to the pmc list.
=> Update myself to PMC list

content/events/release-apache-skywalking-python-1-0-1/index.md, data/docs.yml, data/releases.yml
Vote passed, distribution added, packaged and released.
=> Release Python Agent 1.0.1

content/events/release-apache-skwaylking-rover-0-5-0/index.md, content/events/release-apache-skwaylking-satellite-1-2-0/index.md, content/events/release-apache-skywalking-cli-0-12-0/index.md, data/docs.yml, data/releases.yml
* SkyWalking Satellite 1.2.0
* SkyWalking CLI 0.12.0
* SkyWalking Rover 0.5.0
=> Release SkyWalking Satellite, CLI and Rover

content/events/release-apache-skywalking-cloud-on-kubernetes-0-8-0/index.md, data/docs.yml, data/releases.yml
=> Release swck 0.8.0

content/team/_index.md
=> Move Ye Cao from committer list to pmc list.

content/events/release-apache-skywalking-java-agent-9-0-0/index.md, data/docs.yml, data/releases.yml
=> Release Java agent 9.0.0

content/events/summit-23-cn/index.md
I am just updated by the sponsor team, the venue has been changed due to the time conflict.
We have picked a new place, and I am updating the announcement.
=> Update venue of SkyWalking Summit 2023 Shanghai

README.md, data/docs.yml, data/releases.yml, themes/docsy/layouts/docs/baseof.html
This PR fixes some typos and some minor polishups.
=> Fixup some typos

content/events/welcome-xiang-wei-as-new-committer/index.md
=> Welcome Xiang Wei as new committer

themes/docsy/layouts/partials/head.html, themes/docsy/layouts/partials/scripts.html
See if it works. Idk if I'm doing it correctly. @Jtrust Please take a look.
=> Try fix kapa with CSP for google.com

themes/docsy/layouts/partials/head.html
try to remove the trailing slash to see if it works.
=> Remove trailing slash

.htaccess, config.toml, themes/docsy/layouts/partials/head.html
See https://github.com/apache/apisix-website/pull/1774
=> Fix kapa with htaccess rule

content/quickstart-docker.sh
@wu-sheng where do you expect the doc goes to?
=> Add quick-start script

content/quickstart-docker.sh
This PR fixes the echo statement in line 83 from content/quickstart-docker.sh file
=> Fix typos in statement

content/quickstart-docker.ps1
Fixes:
1. Use throw instead of exit when running scripts from the website. Exit will kill the entire terminal when it's evaluated from the input stream.
2. Download should be by default triggered.
=> Fix powershell quick start bug

content/events/release-apache-skywalking-cloud-on-kubernetes-0-9-0/index.md, data/docs.yml, data/releases.yml
=> Release swck 0.9.0

content/events/welcome-claire-chen-new-committer/index.md, content/team/_index.md
@CzyerChen You have the Apache ID now, you could set it up, and be invited to GitHub ASF org and your account will be Apache committer in all ASF contexts. Then you could review PR and merge other PR after you approve it.
Note, that your PR still needs other's review. We are all same, including myself.
Please review this `event` write and team page update.
=> Welcome Claire Chen as new committer

content/team/_index.md
fix https://github.com/apache/skywalking/issues/12334
=> Fix deadlink.

content/team/_index.md
Update PMC list and format the table.
=> Update PMC list

content/events/release-apache-skywalking-python-1.2.0/index.md, data/docs.yml, data/releases.yml
Release Apache SkyWalking Python 1.2.0
=> Release Apache SkyWalking Python 1.2.0

content/events/release-apache-skywalking-nodejs-0.8.0/index.md, data/docs.yml, data/releases.yml
Release Apache SkyWalking NodeJS 0.8.0
=> Release Apache SkyWalking NodeJS 0.8.0

README.md, themes/docsy/layouts/partials/scripts.html
Source, https://github.com/apache/skywalking-website/pull/794#issuecomment-3106355746
=> Add back Kapa.ai to SkyWalking Website and add user consent

content/events/release-apache-skywalking-java-agent-9-5-0/index.md, data/docs.yml, data/releases.yml
=> Release 9.5.0
